routes/web.php
Route::get('/telas/{tela_id}/proveedor/{proveedor_id}/stock','Planeamiento\\PlaneamientoController@stockTelas');
/**
 * Compras
 */

Route::get('/verifica-guia','Compra\\ComprasController@verifica_guia');
Route::get('/verifica-comprobante','Compra\\ComprasController@verifica_comprobante');

Route::resource('compra/compras', 'Compra\\ComprasController');
Route::get('compras/compras/liquidacion','Compra\\ComprasController@liquidacion')
			->name('compras.liquidacion');
Route::post('compras/compras/liquidar','Compra\\ComprasController@liquidar')
			->name('compras.liquidar');

Route::get('compras/compras/mp','Compra\\ComprasController@recepcion')
			->name('compras.mp');
Route::post('compras/compras/mp','Compras\\ComprasController@recepcionar')
			->name('compras.mp.agregar');
Route::post('compra/compras/existe_lote', 'Compra\\ComprasController@existeLote');

Route::resource('banco/bancos', 'Banco\\BancosController');
Route::resource('tipospago/tipos-pago', 'TiposPago\\TiposPagoController');
Route::resource('cronograma/cronogramas', 'Cronograma\\CronogramasController');

Route::get('cronograma/cronogramas/create/{compra_id}', 'Cronograma\\CronogramasController@create')->name('compra.cronograma.create');
Route::get('compras/accesorios/{id}/lotes','Compra\\ComprasController@accesorios');
Route::get('compras/insumos/{id}/lotes','Compra\\ComprasController@insumos');
Route::get('insumo/{insumo_id}/proveedor/{proveedor_id}/stock','Compra\\ComprasController@insumo_stock');
Route::get('insumo/{lote}/stock','Compra\\ComprasController@mp_stock');

Route::get('lote/{lote}/stock','Compra\\ComprasController@detalleStock')->name('compra.cronograma.create');
Route::get('compras/titulos/{id}/lotes','Compra\\ComprasController@titulo');

Route::resource('recepcion-mp/recepcion-mp','RecepcionMP\\RecepcionMPController');

Route::get('compras/lote/detalles-insumo','Compra\\ComprasController@detallesCompraInsumoByLote');
Route::get('compras/lote/{id}/detalles-accesorio','Compra\\ComprasController@detallesCompraAccesorioByLote');
Route::post('lotesporproveedor', "Compra\ComprasController@getLotesporproveedor");
Route::get('/boletacompra', "Compra\ComprasController@getPdf");

/*
 * Devoluciones
 */
Route::resource('devolucion/devoluciones', 'Devolucion\\DevolucionesController');
Route::resource('detalledevolucion/detalle-devoluciones', 'DetalleDevolucion\\DetalleDevolucionesController');

Route::get('devolucion/compras', 'Devolucion\\DevolucionesController@compras')->name('devolucion.compras');
Route::get('devolucion/devoluciones/create/{compra_id}', 'Devolucion\\DevolucionesController@create')->name('devolucion.compras.create');
Route::get('produccion/{planeamiento_id}/eliminacion','Planeamiento\\PlaneamientoController@eliminacionProduccion');
/*
 * Abonos
 */
Route::resource('tiposabono/tipos-abono', 'TiposAbono\\TiposAbonoController');

Route::resource('abono/abonos', 'Abono\\AbonosController');
Route::resource('detalleabono/detalle-abonos', 'DetalleAbono\\DetalleAbonosController');

Route::get('abono/compras', 'Abono\\AbonosController@compras')->name('abono.compras');
Route::get('abono/abonos/create/{compra_id}', 'Abono\\AbonosController@create')->name('abono.compras.create');

Route::resource('producto/productos', 'Producto\\ProductoController');
Route::resource('compraestado/compra-estados', 'CompraEstado\\CompraEstadosController');



/*
 * Comercializacion
 */
route::group(['middleware'=> 'perfiles'],function(){

Route::get('comercializacion/comercializacion/reporte','Comercializacion\\ComercializacionController@genExcel');
Route::resource('comercializacion/comercializacion','Comercializacion\\ComercializacionController');
route::resource("comercializacion/notaingresoatipico",'Comercializacion\\NotaIngresoAController');
Route::resource('comercializacion/almacen','Comercializacion\\AlmacenController');
Route::resource('comercializacion/transferencia','Comercializacion\\TransferenciaController');
Route::resource('comercializacion/cliente','Comercializacion\\ClienteController');
Route::get('comercializacion/notaingreso/create/{id}', 'Comercializacion\\NotaIngresoController@create')->name('notaingreso.create');
Route::get('comercializacion/notaingreso/editar/{id}', 'Comercializacion\\NotaIngresoController@editar')->name('notaingreso.editar');
Route::get('comercializacion/notaingreso/show/{id}', 'Comercializacion\\NotaIngresoController@show')->name('notaingreso.show');
Route::post('comercializacion/notaingreso/store', 'Comercializacion\\NotaIngresoController@store')->name('notaingreso.store');
Route::get('comercializacion/notaingreso/impresion/{id}', 'Comercializacion\\NotaIngresoController@impresion')->name('notaingreso.impresion');
Route::get('comercializacion/notaingresoatipico/i/impresion', 'Comercializacion\\NotaIngresoAController@impresion')->name('notaingresoatipico.i.impresion');
Route::get('comercializacion/almacen/proalm_create/{id}', 'Comercializacion\\AlmacenController@proalm_create')->name('almacen.proalm_create');
Route::post('comercializacion/almacen/proalm_store/{id}', 'Comercializacion\\AlmacenController@proalm_store')->name('almacen.proalm_store');
Route::delete('comercializacion/almacen/proalm_destroy/{id}', 'Comercializacion\\AlmacenController@proalm_destroy')->name('almacen.proalm_destroy');
Route::get('comercializacion/almacen/proalm_edit/{id}', 'Comercializacion\\AlmacenController@proalm_edit')->name('almacen.proalm_edit');
Route::put('comercializacion/almacen/proalm_update/{id}', 'Comercializacion\\AlmacenController@proalm_update')->name('almacen.proalm_update');
Route::resource('venta','Comercializacion\\VFacturaController');

Route::resource('area','Comercializacion\\AreasController');
Route::resource('areaalmacen','Comercializacion\\Areaalmacen');

Route::get('comercializacion/areaalmacen/proalm_create/{id}', 'Comercializacion\\Areaalmacen@proalm_create')->name('areaalmacen.proalm_create');
Route::post('comercializacion/areaalmacen/proalm_store/{id}', 'Comercializacion\\Areaalmacen@proalm_store')->name('areaalmacen.proalm_store');
Route::delete('comercializacion/areaalmacen/proalm_destroy/{id}', 'Comercializacion\\Areaalmacen@proalm_destroy')->name('areaalmacen.proalm_destroy');
Route::get('comercializacion/areaalmacen/proalm_edit/{id}', 'Comercializacion\\Areaalmacen@proalm_edit')->name('areaalmacen.proalm_edit');
Route::put('comercializacion/areaalmacen/proalm_update/{id}', 'Comercializacion\\Areaalmacen@proalm_update')->name('areaalmacen.proalm_update');


/************************** OPEN CAJA ***************************/
Route::get('comercializacion/caja/abrircaja', 'Comercializacion\\CajaController@abrircaja')->name('caja.abrircaja');
Route::post('comercializacion/caja/abrircaja_store/{id}', 'Comercializacion\\CajaController@abrircaja_store')->name('caja.abrircaja_store');
Route::get('comercializacion/caja/cerrarcaja/{id}', 'Comercializacion\\CajaController@cerrarcaja')->name('caja.cerrarcaja');
Route::post('comercializacion/caja/cerrarcaja_store/{id}', 'Comercializacion\\CajaController@cerrarcaja_store')->name('caja.cerrarcaja_store');
Route::get('comercializacion/caja/transferencia', 'Comercializacion\\CajaController@transferencia')->name('caja.transferencia');
Route::get('comercializacion/caja/index', 'Comercializacion\\CajaController@index')->name('caja.index');
Route::post('comercializacion/caja/transferencia_store/{id}', 'Comercializacion\\CajaController@transferencia_store')->name('caja.transferencia_store');
Route::delete('comercializacion/caja/transferencia_destroy/{id}', 'Comercializacion\\CajaController@transferencia_destroy')->name('caja.transferencia_destroy');
Route::get('comercializacion/caja/reportecajacierre/{id}', 'Comercializacion\\CajaController@reportecajacierre')->name('caja.reportecajacierre');
Route::get('comercializacion/caja/cajaoperaeditar/{id}', 'Comercializacion\\CajaController@cajaoperaeditar')->name('caja.cajaoperaeditar');

Route::put('comercializacion/caja/cajaoperaeditar_put/{id}', 'Comercializacion\\CajaController@cajaoperaeditar_put')->name('caja.cajaoperaeditar_put');

Route::delete('comercializacion/caja/operacion_destroy/{id}', 'Comercializacion\\CajaController@operacion_destroy')->name('caja.operacion_destroy');

Route::resource('comercializacion/notadevolucion','Comercializacion\\NotadevController');
Route::get('comercializacion/notadevolucion/create/{id}', 'Comercializacion\\NotadevController@create')->name('notadevolucion.create');

Route::get('comercializacion/notadevolucion/reporte/{id}', 'Comercializacion\\NotadevController@reporte')->name('notadevolucion.reporte');
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/************************** END CAJA ***************************/
/********** COMPRA DE TELA TEÑIDA ***********/
Route::resource('comercializacion/compraTT','Comercializacion\\CompraTTController');
Route::resource('comercializacion/pagoTT','Comercializacion\\PagoTTController');
Route::get('comercializacion/pagoTT/create/{id}', 'Comercializacion\\PagoTTController@create')->name('pagoTT.create');
/************* END DE COMPRA DE TELA TEÑIDA******/

Route::resource('comercializacion/credito','Comercializacion\\CreditoController');
Route::resource('comercializacion/modulos','Comercializacion\\ModulosControllers');
//Route::get('abono/abonos/create/{compra_id}', 'Abono\\AbonosController@create')->name('abono.compras.create');

//Route::post('comercializacion/notaingreso', 'Comercializacion\\NotaIngresoController@store');

//Reporteria Comercial ----------------
Route::get('comercializacion/reporteria/stockcolores', 'Comercializacion\\ReporteComercialController@stockcolores')->name('reporteria.stockcolores');
Route::get('comercializacion/reporteria/ventaproducto', 'Comercializacion\\ReporteComercialController@ventaproducto')->name('reporteria.ventaproducto');

app/Http/Controllers/Comercializacion/Areaalmacen.php
<?php

namespace App\Http\Controllers\Comercializacion;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Almacen;
use App\ProductoAlmacen;
use App\Areas_almacen;
use App\Areas;
use App\Rols_areas;

use DB;

class Areaalmacen extends Controller
{
	public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
    	$almacens=Almacen::orderBy("nAlmCod","ASC")->paginate(10);
       
    	return view("comercializacion.areaalmacen.index",compact("almacens"));
    }

    public function proalm_store(Request $request,$id)
    {

        $this->validate($request, [
            'area2' => 'required'
        ]);
        
        DB::beginTransaction();

        try 
        {
            $areaalm=new Areas_almacen;
            $areaalm->nAlmCod=$id;
            $areaalm->nAreCod=$request->area2;  
            
            $areaalm->save();        
        } catch (Exception $e) {

            DB::rollback();
            return redirect()->back()->with('info','Ocurrió un error vuelva a intentarlo.');    
        }

        DB::commit();

        return redirect()->route('areaalmacen.proalm_create',compact("id"))->with('info','El área fue agredado al almacén satisfactoriamente.');  
    }

    public function proalm_create(Request $request,$id)
    {
        //$productos=Producto::all();

    	$areas=Areas_almacen::where("nAlmCod","=",$id)->get();
    	$areas2=Areas::whereNotIn("nAreCod",Areas_almacen::select("nAreCod")->where("nAlmCod","=",$id)->get())->get();

        $areaalm=Areas_almacen::where("nAlmCod","=",$id)->Where("nAreCod","like","%".$request->codbus."%")->paginate(5);
        
        $nombrealmacen=Almacen::where("nAlmCod","=",$id)->first();       

        return view("comercializacion.areaalmacen.proalm_create",compact("areas","areas2","areaalm","id","nombrealmacen"));
    }

    public function proalm_destroy($id)
    {       
        $p1=Areas_almacen::where("nAreAlmCod","=",$id)->first();

        if(Rols_areas::where("nAreAlmCod","=",$id)->exists())                             
             return redirect()->route('areaalmacen.index',$id)->with('info','Error: No se pudo eliminar porque el AREA('.$p1->areas->cAreNom.') está relacionado con algún usuario.');
    
        $prodalm1=Areas_almacen::where("nAreAlmCod","=",$id);
        $prodalm1->delete();     
                
        return redirect()->route('areaalmacen.index',$id)->with('info','El área('.$p1->areas->cAreNom.') fue retirada del almacen.');
    }

    public function detallearea(Request $request,$id)
    {
        if($request->ajax()){
            $prod_x=DB::table("rols_areas_modulos")
            ->Join("modulos","rols_areas_modulos.nCodMod","=","modulos.nCodMod") 
            ->where('rols_areas_modulos.nAreCod','=',$id)            
            ->select("modulos.cNomMod","modulos.cDesMod","modulos.url")
            ->distinct()
            ->get();

            return response()->json($prod_x);           
        }
    }


}

app/Http/Controllers/Comercializacion/ClienteController.php
<?php

namespace App\Http\Controllers\Comercializacion;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Cliente; /*Se agregra el nombre del modelo*/
use App\Tipodoc; /*Se agregra el nombre del modelo*/
use Carbon\Carbon;
use App\Http\Requests\ClienteRequest;

class ClienteController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function create()
    {
        $tipodoc=Tipodoc::select('nTdocCod','cTdocSigla')->get();
        return view('comercializacion.cliente.create',compact("tipodoc"));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'tipodoc_id'       => 'required',
            'cClieNdoc'       => 'numeric|required|digits_between:8,15',
            'cClieDesc'       => 'required',
            'cClieDirec'       => 'required'

        ]);
        //dd($request);
        try{
            $cliente = new Cliente;
            $cliente->nTdocCod = $request->tipodoc_id;
            $cliente->cClieNdoc = $request->cClieNdoc;
            $cliente->cClieDesc = $request->cClieDesc;
            $cliente->cClieDirec = $request->cClieDirec;
            $cliente->cClieObs = $request->cClieObs;

            $cliente->save();

        } 
        catch(\Exception $e){
           return redirect()->route('cliente.create')->with('info','Vuelva a intentarlo.');  
        }
        
        return redirect()->route('cliente.index')->with('El cliente fue guardado');        
    }

   public function edit($id)
    {
        $cliente = Cliente::where('nClieCod','=',$id)->get()->first();
        $tipodoc=Tipodoc::select('nTdocCod','cTdocSigla')->get();
        return view('comercializacion.cliente.edit', compact('cliente','tipodoc')); 
    }

   public function update(Request $request,$id)
    {
        $this->validate($request, [
            'tipodoc_id'       => 'required',
            'cClieNdoc'       => 'numeric|required|digits_between:8,15',
            'cClieDesc'       => 'required',
            'cClieDirec'       => 'required'
        ]);
        //dd($request);
        try{
            $fecha_act=Carbon::now()->format('Y-m-d h:i:s');
            Cliente::where('nClieCod',"=",$id)
            ->update([
                'nTdocCod' => $request->tipodoc_id,
                'cClieNdoc' => $request->cClieNdoc,
                'cClieDesc' => $request->cClieDesc,
                'cClieDirec' => $request->cClieDirec,
                'cClieObs' => $request->cClieObs,
                'dFecAct' => $fecha_act
                ]); 
        } 
        catch(\Exception $e){
           return redirect()->route('cliente.edit',$id)->with('info','El cliente no fue actualizado, vuelva a intentarlo.');              
        }
        
        return redirect()->route('cliente.show',$id)->with('info','El cliente fue actualizado.');              
    }

    public function index()
    {
        $cliente = Cliente::where("anulado","0")->orderby('nClieCod', 'ASC')->paginate(5);
        return view('comercializacion.cliente.index', compact('cliente'));
    }

   public function show($id)
    {
        $cliente = Cliente::where('nClieCod','=',$id)->where("anulado","0")->get()->first();
        $tipodoc=Tipodoc::select('nTdocCod','cTdocSigla')->get();
    	return view('comercializacion.cliente.show', compact('cliente','tipodoc'));        
    }

     public function destroy($id)
    {
        try{
            $fecha_elim=Carbon::now()->format('Y-m-d h:i:s');
            Cliente::where('nClieCod',"=",$id)
            ->update([
                'dFecElim' => $fecha_elim,
                'anulado' => '1'
                ]); 

            /*$cliente=cliente::where('nClieCod','=',$id);
            $cliente->delete();*/
        } 
        catch(\Exception $e){
           return redirect()->route('cliente.index',$id)->with('info','Error:No puedo eliminar el registro porque está relacionado con punto de venta');              
        }

        return back()->with('info','El cliente fue eliminado.');
    }
}

app/Http/Controllers/Comercializacion/DetalleNotaIngresoAController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DetalleNotaIngresoAController extends Controller
{
    //
}

app/Http/Controllers/Comercializacion/DetalleNotaIngresoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DetalleNotaIngresoController extends Controller
{
    //
}

app/Http/Controllers/Comercializacion/TiendaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TiendaController extends Controller
{
    public function index()
    {
    	return 'index';
    }
}

resources/views/comercializacion/notadevolucion/index.blade.php
@extends('backend.layouts.appv2')

@section('title', 'BANDEJA DE NOTA DE DEVOLUCIONES')

@section('after-styles')
    <style>
    .dropdown{padding: 0;}
    .dropdown .dropdown-menu{border: 1px solid #999}
    .detallescompra{
        display: none;
        background-color: #ececec;
    }
    </style>
@stop

@section('content')
	
	<div class="row">
		<div class="col-sm-12">
			<section class="content">
			    <div class="box box-info">
			        <div class="box-header with-border">
			            <h3 class="box-title">@yield('title')</h3>
			            <div class="box-tools pull-right">
			                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
			            </div><!-- /.box tools -->
			        </div><!-- /.box-header -->
			        <div class="box-body">
			        	<div class="row">
			        		<form action="{{ route('notadevolucion.index') }}" method="GET">
							{{ csrf_field() }}
							<input type="hidden" name="_method" value="GET">
					        	
					        	<div class="col-md-3">
					        		<label>Fecha</label> 
							        <input class="form-control" type="date" name="fech_b" id="fech_b" step="1" min="2000-01-01" value="{{$rq->fech_b}}" tabindex="1">
							    </div>
							    <div class="col-md-2">
							    	<label>T. Documento</label> 
							        <select class="form-control" name="tdoc_b" id="tdoc_b">
								      	<option value="">...</option>
								      	@foreach($tdoc as $t)
								      		@if($t->nTipPagCod==$rq->tdoc_b)
									        	<option value="{{$t->nTipPagCod}}" selected>{{$t->cDescTipPago}}</option>	
									        @else
									        	<option value="{{$t->nTipPagCod}}">{{$t->cDescTipPago}}</option>	
									        @endif
								        @endforeach
								    </select>							     
							    </div>
							    <div class="col-md-2">
							    	<label>Forma de Pago</label> 
							        <select class="form-control" name="fpago_b" id="fpago_b">
								      	<option value="">...</option>
								      	@foreach($fpago as $t)
								      		@if($t->nForPagCod==$rq->fpago_b)
									        	<option value="{{$t->nForPagCod}}" selected>{{$t->cDescForPag}}</option>	
									        @else
									        	<option value="{{$t->nForPagCod}}">{{$t->cDescForPag}}</option>	
									        @endif									        
								        @endforeach
								    </select>						     
							    </div>
							    <div class="col-md-2">
							    	<label>N°G.Venta/Factura</label> 
							        <input type="text" class="form-control" name="ngven_b" id="ngven_b" maxlength="250" tabindex="1" value="{{$rq->ngven_b}}">						     
							    </div>
							    <div class="col-md-2">
							    	<label>RUC/DNI</label> 
							        <select class="selectpicker form-control" data-show-subtext="true" data-live-search="true" id="rdni" name="rdni">    
							        	<option data-subtext="" value="">...</option>                       
	                                    @foreach($cli as $u)
	                                    	@if($rq->rdni == $u->nClieCod)
	                                    		<option data-subtext="({{$u->cClieNdoc}})" value="{{$u->nClieCod}}" selected>{{$u->cClieDesc}}</option>
	                                    	@else
	                                    		<option data-subtext="({{$u->cClieNdoc}})" value="{{$u->nClieCod}}">{{$u->cClieDesc}}</option>
	                                    	@endif	  
	                                        
	                                    @endforeach
	                                </select>
							    </div>
							    <div class="col-md-1"> 
							    	<label style="color:white;">dd</label>                                	
                                	<button type="submit" class="btn btn-primary"><span class="fa fa-search" aria-hidden="true"></span></button>
	                            </div>
							</form>       
			            </div>
			            
			            <br>
	                    <br>

						@include('comercializacion.venta.fragment.info')
						@include('comercializacion.venta.fragment.error')
						<table class="table table-hover table-striped">
							<thead>
								<tr>
									<!--th>DETALLES</th-->
									
									<th>FECHA</th>	
									<th>T.DOCUMENTO</th>	
									<th>F.PAGO</th>	
									<th>G.VENTA/FACTURA</th>									
									<th>DNI/RUC</th>
									<th>NOMBRE/RAZÓN SOCIAL</th>
									<!--th>SUB-TOTAL</th-->
									<!--th>IGV</th-->									
									<th>TOTAL VENTA</th>
									<th>MONTO A FAVOR</th>
									<th>MONTO EN CONTRA</th>
									<th>TOTAL</th>
									<!--th>ESTADO</th-->
									<th>Nota de Dev.</th>
									<th colspan="3">ACCIONES</th>
								</tr>
							</thead>
							<tbody style="text-align: center;">
								@foreach($vfacturas as $fac)
								<tr>
									<!--td>
										<a class="btn btn-xs btn-success detalle">
											<i class="fa fa-eye fa-1x" id="ver" aria-hidden="true"></i>
										</a>
									</td-->										
									<td>{{ $fac->dVFacFemi }}</td>	
									<td>{{ $fac->tipodocv->cDescTipPago }}</td>									
									<td>{{ $fac->forpago->cDescForPag }}</td>	
									<td>{{ ($fac->nTipPagCod==3)?$fac->cFacNumFac:$fac->nVtaCod }}</td>								
									<td>{{ $fac->cliente->cClieNdoc }}</td>										
									<td>{{ $fac->cliente->cClieDesc}}</td>
									<!--td>{{ $fac->dVFacSTot }}</td>									
									<td>{{ $fac->dVFacIgv }}</td-->
									<td>{{ number_format($fac->dVFacVTot,2) }}</td>
									<td>{{ number_format($fac->devolucion['dMonFavor'],2) }}</td>
									<td>{{ number_format($fac->devolucion['dMonContra'],2) }}</td>
									<td style="font-weight: bold;">{{ number_format(($fac->dVFacVTot-(($fac->devolucion['dMonFavor']=='')?0:$fac->devolucion['dMonFavor'])+(($fac->devolucion['dMonContra']=='')?0:$fac->devolucion['dMonContra'])),2) }}</td>
									<!--td>{{ ($fac->anulado==1)?'Anulado':'Activo'}}</td-->
									<td  style="font-weight: bold;">{{ $fac->devolucion['cDevCod'] }}</td>									
								
									<td>
										@if($fac->anulado==0)												
											@if($fac->devolucion['cDevCod']=='')
												<a href="{{ route('notadevolucion.create',$fac->nVtaCod) }}" class="btn btn-xs btn-success">
													<i class="fa fa-pencil-square-o" data-toggle="tooltip" data-placement="top" title="" data-original-title="Nota de Dev."></i>
												</a>							
											@else
												<a href="{{ route('notadevolucion.show',$fac->nVtaCod) }}" class="btn btn-xs btn-info">
													<i class="fa fa-eye" data-toggle="tooltip" data-placement="top" title="" data-original-title="Ver"></i>
												</a>
												<a href="{{ route('notadevolucion.reporte',$fac->nVtaCod) }}" class="btn btn-xs btn-default" target="_blank">
													<i class="fa fa-print" data-toggle="tooltip" data-placement="top" title="" data-original-title="Imprimir"></i>
												</a> 
											@endif											
											
											<!--a data-method="delete" data-trans-button-cancel="Cancel" data-trans-button-confirm="Anular" data-trans-title="¿Está seguro?" class="btn btn-xs btn-danger" style="cursor:pointer;" onclick="$(this).find(&quot;form&quot;).submit();">
												<i class="fa fa-ban" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete"></i>
												
												<form action="{{ route('venta.update',$fac->nVtaCod) }}" method="POST" name="delete_item" style="display:none">
												   {{ csrf_field() }}
													<input type="hidden" name="_method" value="PUT">
												</form>
											</a-->											
										@else 
											Anulado
										@endif
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
						{!! $vfacturas->render() !!}
						
			        </div><!-- /.box-body -->
			    </div><!--box box-success-->
			</section>
		</div>
	</div>

@endsection

@push('scripts')

<script type="text/javascript">	
    $(document).bind('keydown',function(e){
        if ( e.which == 13 ) 
        {
        	$(location).attr('href',"{{ route('almacen.create') }}");
        };
    });

    /* show / hide order details */
        $(".detalle").click(function() {
          $(this).closest("tr").next().toggle('fast');
          if($("#ver").attr("class") == 'fa fa-eye fa-1x')
            $("#ver").attr("class", "fa fa-eye-slash fa-1x");
          else
            $("#ver").attr("class", "fa fa-eye fa-1x");
        });
</script>

@endpush('scripts')